<?php

namespace ContainerAZWx3IS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SIRl6EhService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sIRl6Eh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sIRl6Eh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'app' => ['privates', '.errored.m32PdeR', NULL, 'Cannot determine controller argument for "Plugin\\DataMigrationBackup30\\Controller\\Admin\\BackupController::deleteAll()": the $app argument is type-hinted with the non-existent class or interface: "Eccube\\Application".'],
        ], [
            'app' => '?',
        ]);
    }
}
