<?php

namespace ContainerAZWx3IS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B4NLZIoService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b4NLZIo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b4NLZIo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'app' => ['privates', '.errored.ZdAuQ2P', NULL, 'Cannot determine controller argument for "Plugin\\DataMigrationBackup30\\Controller\\Admin\\BackupController::scannerScanTheme()": the $app argument is type-hinted with the non-existent class or interface: "Eccube\\Application".'],
        ], [
            'app' => '?',
        ]);
    }
}
