<?php

namespace ContainerLCAjuiU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_DqdlOQRService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.dqdlOQR' shared service.
     *
     * @return \Eccube\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "Plugin\\DataMigrationBackup30\\Controller\\Admin\\BackupController::index()": the $app argument is type-hinted with the non-existent class or interface: "Eccube\\Application".');
    }
}
