<?php
  /**
   * @version EC=CUBE4.3
   * @copyright 株式会社 翔 kakeru.co.jp
   * @author
   * 2026年08月08日作成
   *
   * app\Customize\Repository\Master\KoteColorRepository.php
   *
   *
   * 
   *
   * 
   *                               C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
   ******************************************************/

namespace Customize\Repository\Master;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Customize\Entity\Master\KoteColor;
use Eccube\Repository\AbstractRepository;

/**
 * KoteColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KoteColorRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, KoteColor::class);
    }

    public function selectIdArray()
    {
        $all = $this->findAll();
        $arr = array();
        foreach ($all as $entity) {
            $arr[$entity->getId()] = $entity;
        }
        return $arr;
    }


}
