<?php
/**
 * @version EC=CUBE4.2
 * @copyright 株式会社 翔 kakeru.co.jp
 * @author
 * 2026年09月27日作成
 *
 * app\Customize\Repository\Plugin\CouponRepository.php
 *
 * 
 *
 *
 *
 *                             C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
 ******************************************************/
namespace Customize\Repository\Plugin;

use Eccube\Common\Constant;
use Eccube\Repository\AbstractRepository;
use Plugin\Coupon42\Entity\Coupon;
use Plugin\Coupon42\Entity\CouponDetail;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CouponRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Plugin\Coupon42\Repository\CouponRepository
{
    /**
     * CouponRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry);
    }



    public function couponRemove(\Carbon\Carbon $date)
    {

       $qb = $this->createQueryBuilder('c');

       $qb->update()
          ->set('c.visible', ':upVisible')
          ->setParameter('upVisible', false)
          ->where('c.visible = :visible')     
          ->andWhere('c.available_to_date < :available') 
          ->setParameter('visible', true)
          ->setParameter('available', $date);

        return $qb->getQuery()->execute();
    }

}
