<?php
/**
 * @version EC=CUBE4.2
 * @copyright 株式会社 翔 kakeru.co.jp
 * @author
 * 2026年08月27日作成
 *
 * app\Customize\Repository\Plugin\RecommendProductRepository.php
 *
 * 
 *
 *
 *
 *                             C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
 ******************************************************/

namespace Customize\Repository\Plugin;

use Eccube\Entity\Master\ProductStatus;
use Eccube\Repository\AbstractRepository;
use Plugin\Recommend42\Entity\RecommendProduct;
use Doctrine\Persistence\ManagerRegistry; 
use Customize\Entity\Master\RecommendType;

/**
 * RecommendProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendProductRepository extends \Plugin\Recommend42\Repository\RecommendProductRepository
{
    /**
     * CouponRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry);
    }

    /**
     * Find list.
     * 
     * @return mixed
     */
    public function getRecommendList(?array $FormDAta = [])
    {

        if(is_null($FormDAta)){return [];}
        


        $qb = $this->createQueryBuilder('rp')
            ->innerJoin('rp.Product', 'p');
        $qb->where('rp.visible = true');
        $qb->addOrderBy('rp.sort_no', 'DESC');

        if(RecommendType::CATEGORY == $FormDAta['type']->getId()){
            $qb->andwhere('rp.Category = :Category')
               ->setParameter('Category',$FormDAta['Category']);
        }else{
            $qb->andwhere('rp.RecommendKbn = :RecommendKbn')
               ->setParameter('RecommendKbn',$FormDAta['RecommendKbn']);
        }



        return $qb->getQuery()->getResult();
    }

}
