<?php
/**
 * @version EC=CUBE4.3系
 * @copyright 株式会社 翔 kakeru.co.jp
 * @author
 * 2026年09月23日作成
 *
 * app\Customize\Repository\CustomerRepository.php
 *
 *
 * クーポンサービス
 *
 * 　     
 *                          C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
 ******************************************************/

namespace Customize\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Customer;
use Eccube\Entity\Master\CustomerStatus;
#use Eccube\Entity\Master\OrderStatus;
#use Eccube\Entity\Master\Pref;
#use Eccube\Entity\Master\Sex;
#use Eccube\Util\StringUtil;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Eccube\Repository\CustomerRepository
{


    public const COLUMNS = [
        'customer_id' => 'c.id', 'name' => 'c.name01',
    ];

    /**
     * CustomerRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EntityManagerInterface $entityManager
     * @param OrderRepository $orderRepository
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EntityManagerInterface $entityManager,
        OrderRepository $orderRepository,
        EccubeConfig $eccubeConfig
    ) {
        parent::__construct( $registry,$queries,$entityManager,$orderRepository,$eccubeConfig);


    }

    /**
     * 誕生日を抽出する
     * 
     */
    public function findByBirth(string $Month){

        $Status = $this->entityManager->getRepository(CustomerStatus::class)->find(CustomerStatus::ACTIVE);

        $qb = $this->createQueryBuilder('c');
        
       // return $qb->where('SUBSTRING(c.birth, 6, 2) = :month')  
        return $qb->where($qb->expr()->eq('SUBSTRING(c.birth, 6, 2)', ':month'))           
            ->andWhere('c.Status = :status')

            ->andWhere('c.mailmaga_flg = :MailMagaFlg')
            ->setParameter('month', $Month)
            ->setParameter('status', $Status) // 通常会員
            ->setParameter('MailMagaFlg', 1)  //メールマジン
            ->getQuery()
            ->getResult();

    }

}
