<?php
    /**
	 * @version EC=CUBE4.3
	 * @copyright 株式会社 翔 kakeru.co.jp
	 * @author
	 * 2026年08月13日作成
	 *
	 * app\Customize\Repository\MemberRepository.php
     *
     *
	 * 
	 *
	 * 							   C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
	 ******************************************************/
    namespace Customize\Repository;

use Doctrine\DBAL\Exception\DriverException;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Doctrine\ORM\NoResultException;
use Eccube\Entity\Member;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Eccube\Repository\MemberRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry);
    }



    /** 管理画面　パスワード変更
     * @param string $key
     * @return member|false
     */
    public function getRenewPass($key){

    
        $qb = $this->createQueryBuilder('m')				
                ->where('m.reset_key = :ResetKey')				
                ->setParameter('ResetKey', $key);			

        try {				
        return   $qb->getQuery()->getSingleResult();				
        
            
        } catch (NoResultException $e) {				
            return false;				
        }				
				

    }

}