<?php
  /**
   * @version EC=CUBE4.3
   * @copyright 株式会社 翔 kakeru.co.jp
   * @author
   * 2026年09月27日作成
   *
   * app\Customize\Repository\OrderItemRepository.php
   *
   * 
   * 
   *
   * 
   *                               C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
   ******************************************************/
namespace Customize\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Doctrine\ORM\EntityManagerInterface;
use Eccube\Entity\OrderItem;
use Eccube\Entity\Master\OrderItemType;
use Eccube\Entity\Product;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Eccube\Repository\OrderItemRepository
{

    /**
     * @var EntityManagerInterface;
     */
    private $em;

    public function __construct(RegistryInterface $registry
                ,EntityManagerInterface $EntityManagerInterface
    )
    {
        parent::__construct($registry);
        $this->em = $EntityManagerInterface;
    }

    public function updateProductTotal(){

        $connection = $this->em->getConnection();
        #生クエリーを実行

        $sql  = 'UPDATE dtb_product p ';
        $sql .= 'JOIN (SELECT oi.product_id,SUM(oi.price * oi.quantity) AS total_sales FROM dtb_order_item oi GROUP BY oi.product_id ) AS s ON p.id = s.product_id ';
        $sql .= 'SET p.total = s.total_sales;';


        $connection->executeStatement($sql);

        return ;

    }
}
