<?php
   /**
	 * @version EC=CUBE4.3
	 * @copyright 株式会社 翔 kakeru.co.jp
	 * @author
	 * 2026年08月20日作成
	 *
	 * 
     * app\Customize\Repository\ShopRepository.php
     *
     *
	 * 
	 *
	 * 							   C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
	 ******************************************************/
    namespace Customize\Repository;

 
    use Eccube\Repository\AbstractRepository;
    use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
    use Customize\Entity\Shop;
	use Eccube\Entity\Product;
	use Customize\Repository\Master\ShopStatusRepository;

   	/**
	 * ShopRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
    class ShopRepository extends AbstractRepository
    {
		/**
		 * @var ShopStatusRepository
	    */
        private $ShopStatusRepository;

        public function __construct(RegistryInterface $registry
					,ShopStatusRepository $ShopStatusRepository
		)
        {
            parent::__construct($registry, Shop::class);
			$this->ShopStatusRepository = $ShopStatusRepository;
        }

		public function select(Product $Product ){

		if ($Product->getId()){
			return [$Product->getShop()];
		}	


        $Status = $this->ShopStatusRepository->find(9);
   		$qb = $this->createQueryBuilder('s')				
	 		->orderBy('s.id', 'ASC')			
      		->where('s.status < :status')				
      		->setParameter('status', $Status);
	
				
      	return $qb->getQuery()->getResult();

		}

    }