<?php
   /**
	 * @version EC=CUBE4.3
	 * @copyright 株式会社 翔 kakeru.co.jp
	 * @author
	 * 2026年08月20日作成
	 *
	 * 
     * app\Customize\Repository\ShopRepository.php
     *
     *
	 * 
	 *
	 * 							   C= C= C= ┌(;･_･)┘ﾄｺﾄｺ
	 ******************************************************/
    namespace Customize\Repository;

 
    use Eccube\Repository\AbstractRepository;
    use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
    use Customize\Entity\Shop;

   	/**
	 * ShopRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
    class ShopRepository extends AbstractRepository
    {
        public function __construct(RegistryInterface $registry)
        {
            parent::__construct($registry, Shop::class);
        }
    }