parameters:
    admin_renew_pass_count_max: 3
    Customize_Yaml_dir: '%kernel.project_dir%/app/Customize/Resource/Yaml/'
    coupon_birthday_discountRate: 10
    coupon_entry_discountRate: 5
    coupon_remove_date: 60 #クーポン終了日から非表示にする
    html_user_data_dir: '%eccube_html_dir%/user_data'
    html_user_data_root: '%env(ECCUBE_COOKIE_PATH)%html/user_data'
services:
    Customize\EventListener\RenewPassEventListener:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Eccube\Common\EccubeConfig'
            - '@Customize\Service\MailService'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        tags:
            #- { name: kernel.event_subscriber }
            # 1. 管理画面用のルートに繋ぐ
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\CheckPassportEvent, method: onAdminCheckPassport, dispatcher: security.event_dispatcher.admin }
            # 会員（customer）の認証時は、このクラスの onCustomerCheckPassport を動かす
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\CheckPassportEvent, method: onCustomerCheckPassport, dispatcher: security.event_dispatcher.customer }
    Customize\Controller\ShoppingController:
        autowire: true 
        autoconfigure: true 
        arguments:
            $serviceContainer: !tagged_locator { tag: 'eccube_payment_method' }
        tags: [ 'controller.service_arguments' ]  
    #Customize\Repository\OrderRepository:
    #    decorates: Eccube\Repository\OrderRepository # 差し替え元（デフォルトのEccube側）を上書き指定する
    #    arguments: true
    #Eccube\Repository\OrderRepository:
    #    class: Customize\Repository\OrderRepository
    #    autowire: true