<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAZWx3IS\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAZWx3IS/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAZWx3IS.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAZWx3IS\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerAZWx3IS\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'AZWx3IS',
    'container.build_id' => 'c9c89576',
    'container.build_time' => 1786012058,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAZWx3IS');
