<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Upol8U\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Upol8U/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Upol8U.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Upol8U\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \Container6Upol8U\Eccube_KernelDevDebugContainer([
    'container.build_hash' => '6Upol8U',
    'container.build_id' => '248056e4',
    'container.build_time' => 1786778583,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Upol8U');
